-- Add columns for the employee onboarding form
ALTER TABLE staff ADD COLUMN IF NOT EXISTS date_of_birth DATE;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS gender TEXT CHECK (gender IN ('Male', 'Female', 'Other'));
ALTER TABLE staff ADD COLUMN IF NOT EXISTS national_id TEXT;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS emergency_contact_name TEXT;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS emergency_contact_number TEXT;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS photo_url TEXT;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS medical_license_number TEXT;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS specialization TEXT;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS years_of_experience INTEGER;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS qualifications TEXT;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS certifications TEXT[];
ALTER TABLE staff ADD COLUMN IF NOT EXISTS registration_body TEXT;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS verification_status TEXT DEFAULT 'pending' CHECK (verification_status IN ('pending', 'verified', 'rejected'));
ALTER TABLE staff ADD COLUMN IF NOT EXISTS system_username TEXT;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS system_password_temp TEXT;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS access_role TEXT;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS account_status TEXT DEFAULT 'active' CHECK (account_status IN ('active', 'suspended', 'pending_verification'));
ALTER TABLE staff ADD COLUMN IF NOT EXISTS two_factor_enabled BOOLEAN DEFAULT false;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS password_reset_on_login BOOLEAN DEFAULT true;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS base_salary NUMERIC(12,2);
ALTER TABLE staff ADD COLUMN IF NOT EXISTS housing_allowance NUMERIC(12,2) DEFAULT 0;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS transport_allowance NUMERIC(12,2) DEFAULT 0;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS medical_allowance NUMERIC(12,2) DEFAULT 0;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS overtime_rate NUMERIC(12,2) DEFAULT 0;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS bank_account TEXT;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS tax_id TEXT;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS payment_frequency TEXT DEFAULT 'Monthly' CHECK (payment_frequency IN ('Monthly', 'Bi-weekly'));
ALTER TABLE staff ADD COLUMN IF NOT EXISTS work_days TEXT[] DEFAULT '{"Mon","Tue","Wed","Thu","Fri"}';
ALTER TABLE staff ADD COLUMN IF NOT EXISTS emergency_duty_eligible BOOLEAN DEFAULT false;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS rotation_schedule BOOLEAN DEFAULT false;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS medical_fitness_status TEXT;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS vaccination_records TEXT;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS background_check_status TEXT DEFAULT 'pending' CHECK (background_check_status IN ('pending', 'passed', 'failed'));
ALTER TABLE staff ADD COLUMN IF NOT EXISTS compliance_approval TEXT DEFAULT 'pending' CHECK (compliance_approval IN ('pending', 'approved', 'rejected'));
ALTER TABLE staff ADD COLUMN IF NOT EXISTS documents TEXT[];
ALTER TABLE staff ADD COLUMN IF NOT EXISTS draft BOOLEAN DEFAULT false;
